spring.application.name=Cau4
server.port=8081
#Kết nối database
spring.datasource.url=jdbc:postgresql://localhost:5432/cau4_ss04
spring.datasource.username=postgres
spring.datasource.password=Vucongtien123
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
