spring.application.name=ride-hailing-management

#K?t noi db
spring.datasource.url=jdbc:postgresql://localhost:5432/quan_ly_dat_xe
spring.datasource.username=postgres
spring.datasource.password=Vucongtien123
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate/JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
