spring.application.name=demo_Query
Server.port=8081
#K?t n?i database
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_query
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Vucongtien123

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
