spring.application.name=QuanLyKhoaHoc
# 1. C?u hình c?ng ch?y ?ng d?ng (M?c ??nh là 8080, b?n có th? ??i)
server.port=8080

# 2. C?u hình k?t n?i PostgreSQL
# Thay 'course_management_db' b?ng tên database b?n t?o trong pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management_db
spring.datasource.username=postgres
spring.datasource.password=Vucongtien123
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. C?u hình JPA / Hibernate
# 'update': T? ??ng t?o b?ng ho?c c?p nh?t thêm c?t m?i vào DB mà không xóa d? li?u c?
spring.jpa.hibernate.ddl-auto=update

# Hi?n th? các câu l?nh SQL mà Spring Boot th?c thi xu?ng console (?? b?n d? theo dõi)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ch? ??nh PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. C?u hình Jackson (?? ??nh d?ng ngày tháng khi tr? v? API)
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
# spring.jackson.serialization.write-dates-as-timestamps=false
