spring.application.name=QuanLyKhoaHoc
# 1. C?u hình c?ng ch?y ?ng d?ng (M?c ??nh là 8080, b?n có th? ??i)
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management_db
spring.datasource.username=postgres
spring.datasource.password=Vucongtien123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


