spring.application.name=coursemanagement
# C?u hình k?t n?i PostgreSQL
# C?u hình k?t n?i PostgreSQL (thay postgres/password b?ng tài kho?n máy b?n)
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management_db
spring.datasource.username=postgres
spring.datasource.password=Vucongtien123
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? Hibernate t? ??ng c?p nh?t/t?o b?ng theo Entity
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true